import type { NextPage } from 'next';
import Head from 'next/head';
import Banner from '../components/Banner';
import Cases from '../components/Cases';
import IntroOverlay from '../components/IntroOverlay';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import { useEffect } from 'react';

const Home: NextPage = () => {
  useEffect(() => {
    if (typeof window !== 'undefined') {
      gsap.registerPlugin(ScrollTrigger);
    }
    gsap.to('body', 0, { css: { visibility: 'visible' } });
    // timeline
    const tl = gsap.timeline();
    tl.from(`.index-heading`, {
      duration: 1,
      opacity: 0,
      ease: 'power4.out',
      delay: 1,
      y: 100,
      skewY: 7,
      stagger: {
        amount: 0.3,
      },
    })
      .to('.overlay-top', {
        height: 0,
        duration: 1.6,
        ease: 'expo.inOut',
        stagger: 0.4,
      })
      .to('.overlay-bottom', {
        width: 0,
        duration: 1.6,
        delay: -0.8,
        ease: 'expo.inOut',
        stagger: {
          amount: 0.4,
        },
      })
      .to('.intro-overlay', {
        duration: 0,
        css: {
          display: 'none',
        },
      })
      .from('.case-image', {
        duration: 1.6,
        scale: 1.4,
        ease: 'expo.inOut',
        delay: -2,
        stagger: {
          amount: 0.4,
        },
      });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <IntroOverlay />
        <Banner />
        <Cases />
      </main>
    </>
  );
};

export default Home;
